server:
  port: 8080
  tomcat:
    max-http-form-post-size: 2MB

spring:
  application:
    name: backend

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    # URL lấy từ Supabase (chế độ Transaction Mode hoặc Session Mode)
    url: ${DB_URL:jdbc:postgresql://db.oxqeacydayefsvtsqams.supabase.co:5432/postgres?sslmode=require}
    username: ${DB_USERNAME:postgres}
    password: "DangDuy2005@"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Chuỗi Secret Key lấy từ Settings > API > JWT Secret
          issuer-uri: https://oxqeacydayefsvtsqams.supabase.co/auth/v1
aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:}
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
    bucket-name: ${AWS_S3_BUCKET:default-bucket}
    region: ${AWS_REGION:ap-southeast-1}
    enabled: ${AWS_S3_ENABLED:false}
